#!/bin/sh
#
# Volume control wrapper to support different systems.
#
# Aaron LI
# Created: 2016-01-07
# Updated: 2016-01-07
#
# Loïc Bartoletti
# Update: 2021-12-27
# Update: 2025-02-25 (FreeBSD 14)

# ALSA device/driver (Linux)
ALSA_DEV="Master"
# OSS device (FreeBSD/DragonFly)
OSS_DEV="vol"
OSS_DEFAULT=0.5


if [ $# -ne 1 ]; then
    echo "Usage:"
    echo "    `basename $0` < val | +% | -% | toggle | mute | unmute >"
    exit 1
fi


# amixer: Linux ALSA
vol_amixer() {
    case "$1" in
        toggle)
            amixer set ${ALSA_DEV} toggle
            ;;
        mute)
            amixer set ${ALSA_DEV} mute
            ;;
        unmute)
            amixer set ${ALSA_DEV} unmute
            ;;
        +[1-9]*|-[1-9]*)
            sign=`echo "$1" | cut -c1`
            value="${1#?}"
            amixer set ${ALSA_DEV} "${value}%${sign}" unmute
            ;;
        [1-9]*)
            amixer set ${ALSA_DEV} "$1" unmute
            ;;
        *)
            echo "ERROR: amixer: unknown control command"
            exit 11
            ;;
    esac
}

# mixer: FreeBSD 14 OSS
vol_mixer() {
    # Get current volume value
    current_vol=$(mixer vol | awk -F "=" '/volume/ {print $2}' | cut -d: -f1)
    
    case "$1" in
        toggle)
            if [ "$current_vol" = "0.00" ] || [ "$current_vol" = "0" ]
            then
                # Restore default volume
                mixer vol=${OSS_DEFAULT}
            else
                mixer vol=0
            fi
            ;;
        mute)
            mixer vol=0
            ;;
        unmute)
            mixer vol=${OSS_DEFAULT}
            ;;
        +[0-9]*)
            # Increase volume (format +0.1, +0.05, etc.)
            value="${1#?}"
            # Use awk for decimal math
            new_vol=$(awk "BEGIN {print $current_vol + $value; exit}")
            # Ensure volume doesn't exceed 1
            new_vol=$(awk "BEGIN {print ($new_vol > 1) ? 1 : $new_vol; exit}")
            mixer vol=$new_vol
            ;;
        -[0-9]*)
            # Decrease volume (format -0.1, -0.05, etc.)
            value="${1#?}"
            # Use awk for decimal math
            new_vol=$(awk "BEGIN {print $current_vol - $value; exit}")
            # Ensure volume doesn't go below 0
            new_vol=$(awk "BEGIN {print ($new_vol < 0) ? 0 : $new_vol; exit}")
            mixer vol=$new_vol
            ;;
        [0-9]*)
            # Set volume directly
            # Ensure value is between 0 and 1
            new_vol=$(awk "BEGIN {print ($1 > 1) ? 1 : (($1 < 0) ? 0 : $1); exit}")
            mixer vol=$new_vol
            ;;
        *)
            echo "ERROR: mixer: unknown control command"
            exit 21
            ;;
    esac
}

OS=`uname -s`
case "${OS}" in
    Linux)
        vol_amixer "$1"
        ;;
    FreeBSD|DragonFly)
        vol_mixer "$1"
        ;;
    *)
        echo "ERROR: currently unsupport operating system"
        exit 2
        ;;
esac
