#!/bin/sh
#
# Volume control wrapper to support different systems.
#
# Aaron LI
# Created: 2016-01-07
# Updated: 2016-01-07
#
# Loïc Bartoletti
# Update: 2021-12-27

# ALSA device/driver (Linux)
ALSA_DEV="Master"
# OSS device (FreeBSD/DragonFly)
OSS_DEV="vol"
OSS_DEFAULT=50


if [ $# -ne 1 ]; then
    echo "Usage:"
    echo "    `basename $0` < val | +% | -% | toggle | mute | unmute >"
    exit 1
fi


# amixer: Linux ALSA
vol_amixer() {
    case "$1" in
        toggle)
            amixer set ${ALSA_DEV} toggle
            ;;
        mute)
            amixer set ${ALSA_DEV} mute
            ;;
        unmute)
            amixer set ${ALSA_DEV} unmute
            ;;
        +[1-9]*|-[1-9]*)
            sign=`echo "$1" | cut -c1`
            value="${1#?}"
            amixer set ${ALSA_DEV} "${value}%${sign}" unmute
            ;;
        [1-9]*)
            amixer set ${ALSA_DEV} "$1" unmute
            ;;
        *)
            echo "ERROR: amixer: unknown control command"
            exit 11
            ;;
    esac
}


# mixer: FreeBSD/DragonFly OSS
vol_mixer() {
    volume=`mixer -S ${OSS_DEV} | cut -f2 -d':'`
    case "$1" in
        toggle)
            if [ ${volume} -eq 0 ]
            then
                # TODO: save vol state?
                mixer ${OSS_DEV} ${OSS_DEFAULT}
            else
                mixer ${OSS_DEV} 0
            fi
            ;;
        mute)
            mixer ${OSS_DEV} 0
            ;;
        unmute)
            mixer ${OSS_DEV} ${OSS_DEFAULT}
            ;;
        +[1-9]*|-[1-9]*)
            sign=`echo "$1" | cut -c1`
            value="${1#?}"
            mixer ${OSS_DEV} "${sign}${value}:${sign}${value}"
            ;;
        [1-9]*)
            mixer ${OSS_DEV} "$1:$1"
            ;;
        *)
            echo "ERROR: mixer: unknown control command"
            exit 21
            ;;
    esac
}


OS=`uname -s`
case "${OS}" in
    Linux)
        vol_amixer "$1"
        ;;
    FreeBSD|DragonFly)
        vol_mixer "$1"
        ;;
    *)
        echo "ERROR: currently unsupport operating system"
        exit 2
        ;;
esac
